name: Check leaks
on: [push]
jobs:
  build:
    name: Check leaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@master
